import { HugeiconsIcon } from "@hugeicons/react"
import type { IconSvgElement } from "@hugeicons/react"
import {
  ArrowUp02Icon,
  PlusSignIcon,
  ToolsIcon,
  Cancel01Icon,
  Tag01Icon,
  Brain02Icon,
  CheckListIcon,
  AlarmClockIcon,
  File02Icon,
  SourceCodeCircleIcon,
  Image02Icon,
  InformationCircleIcon,
  Link01Icon,
  Notification03Icon,
  PackageOpenIcon,
  SquareArrowUpRight02Icon,
  Target02Icon,
  StarsIcon,
  Layers01Icon,
  FolderKanbanIcon,
  GridViewIcon,
  PictureInPictureOnIcon,
  Shield01Icon,
  TimeScheduleIcon,
  CubeIcon,
  CropIcon,
  ImageCompositionIcon,
  SentIcon,
  SidebarLeftIcon,
  SidebarRightIcon,
} from "@hugeicons/core-free-icons"

export {
  HugeiconsIcon,
  ArrowUp02Icon,
  PlusSignIcon,
  ToolsIcon,
  Cancel01Icon,
  Tag01Icon,
  Brain02Icon,
  CheckListIcon,
  AlarmClockIcon,
  File02Icon,
  SourceCodeCircleIcon,
  Image02Icon,
  InformationCircleIcon,
  Link01Icon,
  Notification03Icon,
  PackageOpenIcon,
  SquareArrowUpRight02Icon,
  Target02Icon,
  StarsIcon,
  Layers01Icon,
  FolderKanbanIcon,
  GridViewIcon,
  PictureInPictureOnIcon,
  Shield01Icon,
  TimeScheduleIcon,
  CubeIcon,
  CropIcon,
  ImageCompositionIcon,
  SentIcon,
  SidebarLeftIcon,
  SidebarRightIcon,
}

export type { IconSvgElement }
